org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
loader_name=neoforge
neo_version=21.11.42

mod_id=mdm
archives_base_name=mdm
mod_name=Modern Decorations Mod
mod_version=26.10
mod_group_id=com.cookiecraftmods
