plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.mod_version
base.archivesName = project.archives_base_name

tasks.withType(org.gradle.api.tasks.bundling.AbstractArchiveTask).configureEach {
    archiveVersion = "${project.mod_version}-${project.loader_name}-${project.minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.190"

    runs {
        client {
            client()

            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.each { arg ->
                    jvmArgument(arg)
                }
            }
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        mcreator {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

apply from: 'mcreator.gradle'

sourceSets.main.resources {
    srcDir rootProject.file('../../shared/src/main/resources')
}

sourceSets.main.java {
    srcDir rootProject.file('../../shared/src/mc_1.21.1/java')
}

apply from: rootProject.file('../../shared/gradle/validate-recipes.gradle')
