package com.cookiecraftmods.mdm.init;

import com.cookiecraftmods.mdm.registry.ModRegistryEntry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import com.cookiecraftmods.mdm.item.LightOakFurniturePartsItem;

import java.util.function.Supplier;

public class MdmModItems {
	public static final ModRegistryEntry<Item> BLACK_MODERN_FRIDGE_1;
	public static final ModRegistryEntry<Item> LEAFLESS_BAMBOO_DECORATION_1;
	public static final ModRegistryEntry<Item> LEAFLESS_BAMBOO_DECORATION_2;
	public static final ModRegistryEntry<Item> LEAFLESS_BAMBOO_DECORATION_3;
	public static final ModRegistryEntry<Item> BLACK_MODER_STAIRS;
	public static final ModRegistryEntry<Item> WHITE_MODERN_STAIRS;
	public static final ModRegistryEntry<Item> RED_MODERN_STAIRS;
	public static final ModRegistryEntry<Item> BLUE_MODERN_STAIRS;
	public static final ModRegistryEntry<Item> GREEN_MODERN_STAIRS;
	public static final ModRegistryEntry<Item> STEEL_SHELF;
	public static final ModRegistryEntry<Item> BLACK_LAMP;
	public static final ModRegistryEntry<Item> COUCHLEFT;
	public static final ModRegistryEntry<Item> COUCHMIDDLE;
	public static final ModRegistryEntry<Item> COUCH_RIGHT;
	public static final ModRegistryEntry<Item> COUCH_CORNER;
	public static final ModRegistryEntry<Item> SOFA;
	public static final ModRegistryEntry<Item> HAND_SOAP_AND_CREAM_SET;
	public static final ModRegistryEntry<Item> TOILET_PAPER_ROLL;
	public static final ModRegistryEntry<Item> SOAP_BAR;
	public static final ModRegistryEntry<Item> TOILET;
	public static final ModRegistryEntry<Item> BATHROOM_SINK;
	public static final ModRegistryEntry<Item> BATHROOM_SINK_WITH_SHELF;
	public static final ModRegistryEntry<Item> BLACK_WASHBASIN_TAP;
	public static final ModRegistryEntry<Item> WHITE_BATHROOM_SHELF;
	public static final ModRegistryEntry<Item> RING_LAMP;
	public static final ModRegistryEntry<Item> WHITE_BATHTUB;
	public static final ModRegistryEntry<Item> TOWEL_SET_1;
	public static final ModRegistryEntry<Item> TOOTHBRUSHES;
	public static final ModRegistryEntry<Item> CHLOTHESBIN;
	public static final ModRegistryEntry<Item> BATHROOM_STAND;
	public static final ModRegistryEntry<Item> PILE_OF_TOWELS;
	public static final ModRegistryEntry<Item> WALKIN_SHOWER;
	public static final ModRegistryEntry<Item> RAIN_SHOWER;
	public static final ModRegistryEntry<Item> BLACK_OFFICE_DESK;
	public static final ModRegistryEntry<Item> BLACK_DESK_EXTENSION_1;
	public static final ModRegistryEntry<Item> BLACK_DESK_EXTENSION_2;
	public static final ModRegistryEntry<Item> BLACK_DESK_EXTENSION_3;
	public static final ModRegistryEntry<Item> OFFICE_CABINET_1;
	public static final ModRegistryEntry<Item> OFFICE_CABINET_2;
	public static final ModRegistryEntry<Item> OFFICE_CABINET_3;
	public static final ModRegistryEntry<Item> OFFICE_SHELF;
	public static final ModRegistryEntry<Item> BATHROOM_MIRROR;
	public static final ModRegistryEntry<Item> MODERN_DESK_1;
	public static final ModRegistryEntry<Item> MODERN_DESK_2;
	public static final ModRegistryEntry<Item> SHELF;
	public static final ModRegistryEntry<Item> HANGING_SHELF;
	public static final ModRegistryEntry<Item> CARPET_1;
	public static final ModRegistryEntry<Item> BLACK_DESK_LAMP;
	public static final ModRegistryEntry<Item> MODERN_LAMP_1;
	public static final ModRegistryEntry<Item> MODERN_DESK_LAMP_1;
	public static final ModRegistryEntry<Item> MODERN_CHANDELIER_1;
	public static final ModRegistryEntry<Item> SET_1_CABINET;
	public static final ModRegistryEntry<Item> SET_1_CABINET_WITH_DRAWERS;
	public static final ModRegistryEntry<Item> SET_1_CORNER_CABINET_1;
	public static final ModRegistryEntry<Item> SET_1_CORNER_CABINET_2;
	public static final ModRegistryEntry<Item> SET_1_ISLAND_1;
	public static final ModRegistryEntry<Item> SET_1_ISLAND_2;
	public static final ModRegistryEntry<Item> SET_1_OVEN_MICROWAVE;
	public static final ModRegistryEntry<Item> SET_1_FRIDGE;
	public static final ModRegistryEntry<Item> SET_1_CABINET_2;
	public static final ModRegistryEntry<Item> SET_1_HANGING_CABINET;
	public static final ModRegistryEntry<Item> SET_1_CORNER_HANGING_CABINET;
	public static final ModRegistryEntry<Item> DOCUMENT_FOLDERS;
	public static final ModRegistryEntry<Item> SET_2_CABINET_1;
	public static final ModRegistryEntry<Item> SET_2_CABINET_2;
	public static final ModRegistryEntry<Item> SET_2_CABINET_3;
	public static final ModRegistryEntry<Item> SET_2_CABINET_WITH_DRAWERS;
	public static final ModRegistryEntry<Item> SET_2_HANGING_SHELF;
	public static final ModRegistryEntry<Item> SET_2_CORNER_COUNTER;
	public static final ModRegistryEntry<Item> BASKETS;
	public static final ModRegistryEntry<Item> OVEN;
	public static final ModRegistryEntry<Item> INDUCTION_COOKER;
	public static final ModRegistryEntry<Item> TV_STAND_MID;
	public static final ModRegistryEntry<Item> TV_STAND_LEFT;
	public static final ModRegistryEntry<Item> TV_STAND_RIGHT;
	public static final ModRegistryEntry<Item> TV_STAND_MID_DECORATED;
	public static final ModRegistryEntry<Item> POOL_TABLE;
	public static final ModRegistryEntry<Item> POTTED_TREE;
	public static final ModRegistryEntry<Item> OUTDOOR_COUCH;
	public static final ModRegistryEntry<Item> OUTDOOR_TABLE;
	public static final ModRegistryEntry<Item> LANTERN;
	public static final ModRegistryEntry<Item> STREET_LANTERN_BOTTOM;
	public static final ModRegistryEntry<Item> STREET_LANTERN_MID;
	public static final ModRegistryEntry<Item> STREET_LATERN_TOP;
	public static final ModRegistryEntry<Item> CEILLING_FAN;
	public static final ModRegistryEntry<Item> SET_1_NIGHT_TABLE;
	public static final ModRegistryEntry<Item> SET_1_BED;
	public static final ModRegistryEntry<Item> SET_1_FOOTREST;
	public static final ModRegistryEntry<Item> LIGHT_GREY_COUCH_MIDDLE;
	public static final ModRegistryEntry<Item> LIGHT_GRAY_COUCH_LEFT;
	public static final ModRegistryEntry<Item> LIGHT_GREY_COUCH_RIGHT;
	public static final ModRegistryEntry<Item> GREY_COUCH_MIDDLE;
	public static final ModRegistryEntry<Item> GREY_COUCH_LEFT;
	public static final ModRegistryEntry<Item> GREY_COUCH_RIGHT;
	public static final ModRegistryEntry<Item> GREY_COUCH_CORNER;
	public static final ModRegistryEntry<Item> GREY_SOFA;
	public static final ModRegistryEntry<Item> SET_1_COFFE_TABLE_1_SHORT;
	public static final ModRegistryEntry<Item> SET_1_COFFE_TABLE_1_TALL;
	public static final ModRegistryEntry<Item> SET_1_COFFE_TABLE_2;
	public static final ModRegistryEntry<Item> SET_3_COFFE_TABLE;
	public static final ModRegistryEntry<Item> SET_3_COFFE_TABLE_DECORATED;
	public static final ModRegistryEntry<Item> SET_3TV_STAND;
	public static final ModRegistryEntry<Item> SET_1_TV_STAND;
	public static final ModRegistryEntry<Item> SET_1_TV_STAND_MIDDLE;
	public static final ModRegistryEntry<Item> BLACK_WALL_CLOCK;
	public static final ModRegistryEntry<Item> WOODEN_WALL_CLOCK;
	public static final ModRegistryEntry<Item> SET_1_CHAIR;
	public static final ModRegistryEntry<Item> SET_1_LIVINGROOM_CABINET;
	public static final ModRegistryEntry<Item> SET_1_LIVINGROOM_CABINET_2;
	public static final ModRegistryEntry<Item> SET_1_COFFEE_TABLE_2_MIDDLE;
	public static final ModRegistryEntry<Item> SET_1_LIVINGROOM_HANGING_CABINET;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_CORNER_COUNTER;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_CORNER_COUNTER_WITH_SINK;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_COUNTER;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_COUNTER_2;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_COUNTER_3;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_DISHWASHER;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_FRIDGE_BOTTOM;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_FRIDGE_TOP;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_HANGING_CABINET;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_OVEN_BOTTOM;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_OVEN_TOP;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_SMALL_CORNER_HANGING_CABINET;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_SMALL_HANGING_CABINET;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_HANGING_CORNER_CABINET;
	public static final ModRegistryEntry<Item> GAS_STOVE;
	public static final ModRegistryEntry<Item> KITCHEN_SET_3_BAR_CHAIR;
	public static final ModRegistryEntry<Item> BEDROOMSET_1_BLACK_LOVESEAT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREYDRESSERLEFT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREYDRESSERMID;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREYDRESSERRIGHT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREY_SINGLE_BED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREY_DOUBLE_BED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREY_BUNK_BED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREYWARDROBE;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREYLOVESEAT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREY_NIGHTSTAND_1;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1GREY_NIGHTSTAND_2;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGEBUNKBED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGE_DOUBLE_BED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGE_SINGLE_BED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGEDRESSERMID;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGEDRESSERLEFT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGEDRESSERRIGHT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGEWARDROBE;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGENIGHTSTAND_1;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WENGENIGHSTAND_2;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITEBUNKBED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITE_DOUBLEBED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITE_SINGLEBED;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITEDRESSERLEFT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITEDRESSERMID;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITEDRESSERRIGHT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITEWARDROBE;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITELOVESEAT;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITENIGHTSTAND_1;
	public static final ModRegistryEntry<Item> BEDROOM_SET_1WHITENIGHSTAND_2;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_2_MID;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_2_SIDE;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_2_SIDE_VAR_2;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_BOOKSHELF_VAR_1_BOTTOM;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_BOOKSHELF_VAR_1_TOP;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_SHELF_VAR_1_BOTTOM;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_SHELF_VAR_1_TOP;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_SHELF_VAR_2_BOTTOM;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_SHELF_VAR_2_TOP;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_CABINET;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_CABINET_VAR_2;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_CABINET_VAR_3;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_CABINET_VAR_4;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_LEFT;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_LEFT_VAR_2;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_LEFT_VAR_3;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_MIDDLE;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_RIGHT;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_RIGHT_VAR_2;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_1_RIGHT_VAR_3;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_CHAIR;
	public static final ModRegistryEntry<Item> OFFICE_SET_1_DESK_LAMP;
	public static final ModRegistryEntry<Item> FURNITURE_PARTS;
	public static final ModRegistryEntry<Item> BLACK_BENCH;
	public static final ModRegistryEntry<Item> WHITE_BENCH;
	public static final ModRegistryEntry<Item> CARPET_2;
	public static final ModRegistryEntry<Item> CARPET_3;
	public static final ModRegistryEntry<Item> CARPET_4;
	public static final ModRegistryEntry<Item> WHITE_BOARD;
	public static final ModRegistryEntry<Item> STANDING_WHITE_BOARD;
	public static final ModRegistryEntry<Item> CORK_BOARD;
	public static final ModRegistryEntry<Item> MODERN_PAINTING;
	public static final ModRegistryEntry<Item> MODERN_PAINTING_2;
	public static final ModRegistryEntry<Item> WHITE_CURTAIN;
	public static final ModRegistryEntry<Item> WHITE_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> WHITE_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> RED_CURTAIN;
	public static final ModRegistryEntry<Item> RED_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> RED_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> CURTAIN_RACK;
	public static final ModRegistryEntry<Item> BLACK_CURTAIN;
	public static final ModRegistryEntry<Item> BLACK_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> BLACK_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> GREY_CURTAIN;
	public static final ModRegistryEntry<Item> GREY_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> GREY_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> BLUE_CURTAIN;
	public static final ModRegistryEntry<Item> BLUE_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> BLUE_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> GREEN_CURTAIN;
	public static final ModRegistryEntry<Item> GREEN_CURTAIN_LEFT;
	public static final ModRegistryEntry<Item> GREEN_CURTAIN_RIGHT;
	public static final ModRegistryEntry<Item> FOYER_WALL_UNIT_BOTTOM;
	public static final ModRegistryEntry<Item> FOYER_WALL_UNIT_TOP;
	public static final ModRegistryEntry<Item> WHITE_WOOD_FOYER_WALL_UNIT;
	public static final ModRegistryEntry<Item> WHITE_WOOD_FOYER_WALL_UNIT_TOP;
	public static final ModRegistryEntry<Item> BLACK_FOYER_WALL_UNIT;
	public static final ModRegistryEntry<Item> BLACK_FOYER_WALL_UNIT_TOP;
	public static final ModRegistryEntry<Item> WHITE_ARMCHAIR;
	public static final ModRegistryEntry<Item> BLACK_ARMCHAIR;
	public static final ModRegistryEntry<Item> SMALL_TABLE;
	public static final ModRegistryEntry<Item> SMALL_CHANDELIER;
	public static final ModRegistryEntry<Item> SMALL_CEILING_LAMP;
	public static final ModRegistryEntry<Item> BIG_CEILING_LIGHT;
	public static final ModRegistryEntry<Item> BIG_CEILING_LAMP;
	public static final ModRegistryEntry<Item> BATHROOM_RADIATOR;
	public static final ModRegistryEntry<Item> BATHROOM_SHELF_02;
	public static final ModRegistryEntry<Item> BOWL;
	public static final ModRegistryEntry<Item> CHOPPING_BOARD;
	public static final ModRegistryEntry<Item> COFFEE_TABLE_04;
	public static final ModRegistryEntry<Item> CRIB;
	public static final ModRegistryEntry<Item> FORK;
	public static final ModRegistryEntry<Item> KNIFE;
	public static final ModRegistryEntry<Item> KNIFE_STAND;
	public static final ModRegistryEntry<Item> LAMP_03;
	public static final ModRegistryEntry<Item> MUG;
	public static final ModRegistryEntry<Item> PAINTING_05;
	public static final ModRegistryEntry<Item> PLATE;
	public static final ModRegistryEntry<Item> POTTED_CACTUS;
	public static final ModRegistryEntry<Item> POUF;
	public static final ModRegistryEntry<Item> SEASONING_RACK;
	public static final ModRegistryEntry<Item> SPOON;
	public static final ModRegistryEntry<Item> WALL_LAMP;
	public static final ModRegistryEntry<Item> WALL_LAMP_2;
	public static final ModRegistryEntry<Item> WINDOW_BLINDS;
	public static final ModRegistryEntry<Item> SHOJI_SCREEN;
	public static final ModRegistryEntry<Item> PAINTING_03;
	public static final ModRegistryEntry<Item> PAINTING_04;
	public static final ModRegistryEntry<Item> BOXES;
	public static final ModRegistryEntry<Item> COAT_HANGER;
	public static final ModRegistryEntry<Item> DOOR_MAT;
	public static final ModRegistryEntry<Item> ELECTRIC_GUITAR_BLACK;
	public static final ModRegistryEntry<Item> ELECTRIC_GUITAR_WITH_STAND;
	public static final ModRegistryEntry<Item> ENTRYWAY_CARPET;
	public static final ModRegistryEntry<Item> FOYER_BENCH;
	public static final ModRegistryEntry<Item> FOYER_BENCH_DARK;
	public static final ModRegistryEntry<Item> FOYER_BENCH_WHITE;
	public static final ModRegistryEntry<Item> FOYER_BENCH_WENGE;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS_2;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS_3;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS_4;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS_5;
	public static final ModRegistryEntry<Item> PAIR_OF_BOOTS_6;
	public static final ModRegistryEntry<Item> SHOE_RACK;
	public static final ModRegistryEntry<Item> SHOE_RACK_2;
	public static final ModRegistryEntry<Item> SHOE_RACK_3;
	public static final ModRegistryEntry<Item> TALL_MIRROR;
	static {
		BLACK_MODERN_FRIDGE_1 = block(MdmModBlocks.BLACK_MODERN_FRIDGE_1);
		LEAFLESS_BAMBOO_DECORATION_1 = block(MdmModBlocks.LEAFLESS_BAMBOO_DECORATION_1);
		LEAFLESS_BAMBOO_DECORATION_2 = block(MdmModBlocks.LEAFLESS_BAMBOO_DECORATION_2);
		LEAFLESS_BAMBOO_DECORATION_3 = block(MdmModBlocks.LEAFLESS_BAMBOO_DECORATION_3);
		BLACK_MODER_STAIRS = block(MdmModBlocks.BLACK_MODER_STAIRS);
		WHITE_MODERN_STAIRS = block(MdmModBlocks.WHITE_MODERN_STAIRS);
		RED_MODERN_STAIRS = block(MdmModBlocks.RED_MODERN_STAIRS);
		BLUE_MODERN_STAIRS = block(MdmModBlocks.BLUE_MODERN_STAIRS);
		GREEN_MODERN_STAIRS = block(MdmModBlocks.GREEN_MODERN_STAIRS);
		STEEL_SHELF = block(MdmModBlocks.STEEL_SHELF);
		BLACK_LAMP = block(MdmModBlocks.BLACK_LAMP);
		COUCHLEFT = block(MdmModBlocks.COUCHLEFT);
		COUCHMIDDLE = block(MdmModBlocks.COUCHMIDDLE);
		COUCH_RIGHT = block(MdmModBlocks.COUCH_RIGHT);
		COUCH_CORNER = block(MdmModBlocks.COUCH_CORNER);
		SOFA = block(MdmModBlocks.SOFA);
		HAND_SOAP_AND_CREAM_SET = block(MdmModBlocks.HAND_SOAP_AND_CREAM_SET);
		TOILET_PAPER_ROLL = block(MdmModBlocks.TOILET_PAPER_ROLL);
		SOAP_BAR = block(MdmModBlocks.SOAP_BAR);
		TOILET = block(MdmModBlocks.TOILET);
		BATHROOM_SINK = block(MdmModBlocks.BATHROOM_SINK);
		BATHROOM_SINK_WITH_SHELF = block(MdmModBlocks.BATHROOM_SINK_WITH_SHELF);
		BLACK_WASHBASIN_TAP = block(MdmModBlocks.BLACK_WASHBASIN_TAP);
		WHITE_BATHROOM_SHELF = block(MdmModBlocks.WHITE_BATHROOM_SHELF);
		RING_LAMP = block(MdmModBlocks.RING_LAMP);
		WHITE_BATHTUB = block(MdmModBlocks.WHITE_BATHTUB);
		TOWEL_SET_1 = block(MdmModBlocks.TOWEL_SET_1);
		TOOTHBRUSHES = block(MdmModBlocks.TOOTHBRUSHES);
		CHLOTHESBIN = block(MdmModBlocks.CHLOTHESBIN);
		BATHROOM_STAND = block(MdmModBlocks.BATHROOM_STAND);
		PILE_OF_TOWELS = block(MdmModBlocks.PILE_OF_TOWELS);
		WALKIN_SHOWER = block(MdmModBlocks.WALKIN_SHOWER);
		RAIN_SHOWER = block(MdmModBlocks.RAIN_SHOWER);
		BLACK_OFFICE_DESK = block(MdmModBlocks.BLACK_OFFICE_DESK);
		BLACK_DESK_EXTENSION_1 = block(MdmModBlocks.BLACK_DESK_EXTENSION_1);
		BLACK_DESK_EXTENSION_2 = block(MdmModBlocks.BLACK_DESK_EXTENSION_2);
		BLACK_DESK_EXTENSION_3 = block(MdmModBlocks.BLACK_DESK_EXTENSION_3);
		OFFICE_CABINET_1 = block(MdmModBlocks.OFFICE_CABINET_1);
		OFFICE_CABINET_2 = block(MdmModBlocks.OFFICE_CABINET_2);
		OFFICE_CABINET_3 = block(MdmModBlocks.OFFICE_CABINET_3);
		OFFICE_SHELF = block(MdmModBlocks.OFFICE_SHELF);
		BATHROOM_MIRROR = block(MdmModBlocks.BATHROOM_MIRROR);
		MODERN_DESK_1 = block(MdmModBlocks.MODERN_DESK_1);
		MODERN_DESK_2 = block(MdmModBlocks.MODERN_DESK_2);
		SHELF = block(MdmModBlocks.SHELF);
		HANGING_SHELF = block(MdmModBlocks.HANGING_SHELF);
		CARPET_1 = block(MdmModBlocks.CARPET_1);
		BLACK_DESK_LAMP = block(MdmModBlocks.BLACK_DESK_LAMP);
		MODERN_LAMP_1 = block(MdmModBlocks.MODERN_LAMP_1);
		MODERN_DESK_LAMP_1 = block(MdmModBlocks.MODERN_DESK_LAMP_1);
		MODERN_CHANDELIER_1 = block(MdmModBlocks.MODERN_CHANDELIER_1);
		SET_1_CABINET = block(MdmModBlocks.SET_1_CABINET);
		SET_1_CABINET_WITH_DRAWERS = block(MdmModBlocks.SET_1_CABINET_WITH_DRAWERS);
		SET_1_CORNER_CABINET_1 = block(MdmModBlocks.SET_1_CORNER_CABINET_1);
		SET_1_CORNER_CABINET_2 = block(MdmModBlocks.SET_1_CORNER_CABINET_2);
		SET_1_ISLAND_1 = block(MdmModBlocks.SET_1_ISLAND_1);
		SET_1_ISLAND_2 = block(MdmModBlocks.SET_1_ISLAND_2);
		SET_1_OVEN_MICROWAVE = block(MdmModBlocks.SET_1_OVEN_MICROWAVE);
		SET_1_FRIDGE = block(MdmModBlocks.SET_1_FRIDGE);
		SET_1_CABINET_2 = block(MdmModBlocks.SET_1_CABINET_2);
		SET_1_HANGING_CABINET = block(MdmModBlocks.SET_1_HANGING_CABINET);
		SET_1_CORNER_HANGING_CABINET = block(MdmModBlocks.SET_1_CORNER_HANGING_CABINET);
		DOCUMENT_FOLDERS = block(MdmModBlocks.DOCUMENT_FOLDERS);
		SET_2_CABINET_1 = block(MdmModBlocks.SET_2_CABINET_1);
		SET_2_CABINET_2 = block(MdmModBlocks.SET_2_CABINET_2);
		SET_2_CABINET_3 = block(MdmModBlocks.SET_2_CABINET_3);
		SET_2_CABINET_WITH_DRAWERS = block(MdmModBlocks.SET_2_CABINET_WITH_DRAWERS);
		SET_2_HANGING_SHELF = block(MdmModBlocks.SET_2_HANGING_SHELF);
		SET_2_CORNER_COUNTER = block(MdmModBlocks.SET_2_CORNER_COUNTER);
		BASKETS = block(MdmModBlocks.BASKETS);
		OVEN = block(MdmModBlocks.OVEN);
		INDUCTION_COOKER = block(MdmModBlocks.INDUCTION_COOKER);
		TV_STAND_MID = block(MdmModBlocks.TV_STAND_MID);
		TV_STAND_LEFT = block(MdmModBlocks.TV_STAND_LEFT);
		TV_STAND_RIGHT = block(MdmModBlocks.TV_STAND_RIGHT);
		TV_STAND_MID_DECORATED = block(MdmModBlocks.TV_STAND_MID_DECORATED);
		POOL_TABLE = block(MdmModBlocks.POOL_TABLE);
		POTTED_TREE = block(MdmModBlocks.POTTED_TREE);
		OUTDOOR_COUCH = block(MdmModBlocks.OUTDOOR_COUCH);
		OUTDOOR_TABLE = block(MdmModBlocks.OUTDOOR_TABLE);
		LANTERN = block(MdmModBlocks.LANTERN);
		STREET_LANTERN_BOTTOM = block(MdmModBlocks.STREET_LANTERN_BOTTOM);
		STREET_LANTERN_MID = block(MdmModBlocks.STREET_LANTERN_MID);
		STREET_LATERN_TOP = block(MdmModBlocks.STREET_LATERN_TOP);
		CEILLING_FAN = block(MdmModBlocks.CEILLING_FAN);
		SET_1_NIGHT_TABLE = block(MdmModBlocks.SET_1_NIGHT_TABLE);
		SET_1_BED = block(MdmModBlocks.SET_1_BED);
		SET_1_FOOTREST = block(MdmModBlocks.SET_1_FOOTREST);
		LIGHT_GREY_COUCH_MIDDLE = block(MdmModBlocks.LIGHT_GREY_COUCH_MIDDLE);
		LIGHT_GRAY_COUCH_LEFT = block(MdmModBlocks.LIGHT_GRAY_COUCH_LEFT);
		LIGHT_GREY_COUCH_RIGHT = block(MdmModBlocks.LIGHT_GREY_COUCH_RIGHT);
		GREY_COUCH_MIDDLE = block(MdmModBlocks.GREY_COUCH_MIDDLE);
		GREY_COUCH_LEFT = block(MdmModBlocks.GREY_COUCH_LEFT);
		GREY_COUCH_RIGHT = block(MdmModBlocks.GREY_COUCH_RIGHT);
		GREY_COUCH_CORNER = block(MdmModBlocks.GREY_COUCH_CORNER);
		GREY_SOFA = block(MdmModBlocks.GREY_SOFA);
		SET_1_COFFE_TABLE_1_SHORT = block(MdmModBlocks.SET_1_COFFE_TABLE_1_SHORT);
		SET_1_COFFE_TABLE_1_TALL = block(MdmModBlocks.SET_1_COFFE_TABLE_1_TALL);
		SET_1_COFFE_TABLE_2 = block(MdmModBlocks.SET_1_COFFE_TABLE_2);
		SET_3_COFFE_TABLE = block(MdmModBlocks.SET_3_COFFE_TABLE);
		SET_3_COFFE_TABLE_DECORATED = block(MdmModBlocks.SET_3_COFFE_TABLE_DECORATED);
		SET_3TV_STAND = block(MdmModBlocks.SET_3TV_STAND);
		SET_1_TV_STAND = block(MdmModBlocks.SET_1_TV_STAND);
		SET_1_TV_STAND_MIDDLE = block(MdmModBlocks.SET_1_TV_STAND_MIDDLE);
		BLACK_WALL_CLOCK = block(MdmModBlocks.BLACK_WALL_CLOCK);
		WOODEN_WALL_CLOCK = block(MdmModBlocks.WOODEN_WALL_CLOCK);
		SET_1_CHAIR = block(MdmModBlocks.SET_1_CHAIR);
		SET_1_LIVINGROOM_CABINET = block(MdmModBlocks.SET_1_LIVINGROOM_CABINET);
		SET_1_LIVINGROOM_CABINET_2 = block(MdmModBlocks.SET_1_LIVINGROOM_CABINET_2);
		SET_1_COFFEE_TABLE_2_MIDDLE = block(MdmModBlocks.SET_1_COFFEE_TABLE_2_MIDDLE);
		SET_1_LIVINGROOM_HANGING_CABINET = block(MdmModBlocks.SET_1_LIVINGROOM_HANGING_CABINET);
		KITCHEN_SET_3_CORNER_COUNTER = block(MdmModBlocks.KITCHEN_SET_3_CORNER_COUNTER);
		KITCHEN_SET_3_CORNER_COUNTER_WITH_SINK = block(MdmModBlocks.KITCHEN_SET_3_CORNER_COUNTER_WITH_SINK);
		KITCHEN_SET_3_COUNTER = block(MdmModBlocks.KITCHEN_SET_3_COUNTER);
		KITCHEN_SET_3_COUNTER_2 = block(MdmModBlocks.KITCHEN_SET_3_COUNTER_2);
		KITCHEN_SET_3_COUNTER_3 = block(MdmModBlocks.KITCHEN_SET_3_COUNTER_3);
		KITCHEN_SET_3_DISHWASHER = block(MdmModBlocks.KITCHEN_SET_3_DISHWASHER);
		KITCHEN_SET_3_FRIDGE_BOTTOM = block(MdmModBlocks.KITCHEN_SET_3_FRIDGE_BOTTOM);
		KITCHEN_SET_3_FRIDGE_TOP = block(MdmModBlocks.KITCHEN_SET_3_FRIDGE_TOP);
		KITCHEN_SET_3_HANGING_CABINET = block(MdmModBlocks.KITCHEN_SET_3_HANGING_CABINET);
		KITCHEN_SET_3_OVEN_BOTTOM = block(MdmModBlocks.KITCHEN_SET_3_OVEN_BOTTOM);
		KITCHEN_SET_3_OVEN_TOP = block(MdmModBlocks.KITCHEN_SET_3_OVEN_TOP);
		KITCHEN_SET_3_SMALL_CORNER_HANGING_CABINET = block(MdmModBlocks.KITCHEN_SET_3_SMALL_CORNER_HANGING_CABINET);
		KITCHEN_SET_3_SMALL_HANGING_CABINET = block(MdmModBlocks.KITCHEN_SET_3_SMALL_HANGING_CABINET);
		KITCHEN_SET_3_HANGING_CORNER_CABINET = block(MdmModBlocks.KITCHEN_SET_3_HANGING_CORNER_CABINET);
		GAS_STOVE = block(MdmModBlocks.GAS_STOVE);
		KITCHEN_SET_3_BAR_CHAIR = block(MdmModBlocks.KITCHEN_SET_3_BAR_CHAIR);
		BEDROOMSET_1_BLACK_LOVESEAT = block(MdmModBlocks.BEDROOMSET_1_BLACK_LOVESEAT);
		BEDROOM_SET_1GREYDRESSERLEFT = block(MdmModBlocks.BEDROOM_SET_1GREYDRESSERLEFT);
		BEDROOM_SET_1GREYDRESSERMID = block(MdmModBlocks.BEDROOM_SET_1GREYDRESSERMID);
		BEDROOM_SET_1GREYDRESSERRIGHT = block(MdmModBlocks.BEDROOM_SET_1GREYDRESSERRIGHT);
		BEDROOM_SET_1GREY_SINGLE_BED = block(MdmModBlocks.BEDROOM_SET_1GREY_SINGLE_BED);
		BEDROOM_SET_1GREY_DOUBLE_BED = block(MdmModBlocks.BEDROOM_SET_1GREY_DOUBLE_BED);
		BEDROOM_SET_1GREY_BUNK_BED = block(MdmModBlocks.BEDROOM_SET_1GREY_BUNK_BED);
		BEDROOM_SET_1GREYWARDROBE = block(MdmModBlocks.BEDROOM_SET_1GREYWARDROBE);
		BEDROOM_SET_1GREYLOVESEAT = block(MdmModBlocks.BEDROOM_SET_1GREYLOVESEAT);
		BEDROOM_SET_1GREY_NIGHTSTAND_1 = block(MdmModBlocks.BEDROOM_SET_1GREY_NIGHTSTAND_1);
		BEDROOM_SET_1GREY_NIGHTSTAND_2 = block(MdmModBlocks.BEDROOM_SET_1GREY_NIGHTSTAND_2);
		BEDROOM_SET_1WENGEBUNKBED = block(MdmModBlocks.BEDROOM_SET_1WENGEBUNKBED);
		BEDROOM_SET_1WENGE_DOUBLE_BED = block(MdmModBlocks.BEDROOM_SET_1WENGE_DOUBLE_BED);
		BEDROOM_SET_1WENGE_SINGLE_BED = block(MdmModBlocks.BEDROOM_SET_1WENGE_SINGLE_BED);
		BEDROOM_SET_1WENGEDRESSERMID = block(MdmModBlocks.BEDROOM_SET_1WENGEDRESSERMID);
		BEDROOM_SET_1WENGEDRESSERLEFT = block(MdmModBlocks.BEDROOM_SET_1WENGEDRESSERLEFT);
		BEDROOM_SET_1WENGEDRESSERRIGHT = block(MdmModBlocks.BEDROOM_SET_1WENGEDRESSERRIGHT);
		BEDROOM_SET_1WENGEWARDROBE = block(MdmModBlocks.BEDROOM_SET_1WENGEWARDROBE);
		BEDROOM_SET_1WENGENIGHTSTAND_1 = block(MdmModBlocks.BEDROOM_SET_1WENGENIGHTSTAND_1);
		BEDROOM_SET_1WENGENIGHSTAND_2 = block(MdmModBlocks.BEDROOM_SET_1WENGENIGHSTAND_2);
		BEDROOM_SET_1WHITEBUNKBED = block(MdmModBlocks.BEDROOM_SET_1WHITEBUNKBED);
		BEDROOM_SET_1WHITE_DOUBLEBED = block(MdmModBlocks.BEDROOM_SET_1WHITE_DOUBLEBED);
		BEDROOM_SET_1WHITE_SINGLEBED = block(MdmModBlocks.BEDROOM_SET_1WHITE_SINGLEBED);
		BEDROOM_SET_1WHITEDRESSERLEFT = block(MdmModBlocks.BEDROOM_SET_1WHITEDRESSERLEFT);
		BEDROOM_SET_1WHITEDRESSERMID = block(MdmModBlocks.BEDROOM_SET_1WHITEDRESSERMID);
		BEDROOM_SET_1WHITEDRESSERRIGHT = block(MdmModBlocks.BEDROOM_SET_1WHITEDRESSERRIGHT);
		BEDROOM_SET_1WHITEWARDROBE = block(MdmModBlocks.BEDROOM_SET_1WHITEWARDROBE);
		BEDROOM_SET_1WHITELOVESEAT = block(MdmModBlocks.BEDROOM_SET_1WHITELOVESEAT);
		BEDROOM_SET_1WHITENIGHTSTAND_1 = block(MdmModBlocks.BEDROOM_SET_1WHITENIGHTSTAND_1);
		BEDROOM_SET_1WHITENIGHSTAND_2 = block(MdmModBlocks.BEDROOM_SET_1WHITENIGHSTAND_2);
		OFFICE_SET_1_DESK_2_MID = block(MdmModBlocks.OFFICE_SET_1_DESK_2_MID);
		OFFICE_SET_1_DESK_2_SIDE = block(MdmModBlocks.OFFICE_SET_1_DESK_2_SIDE);
		OFFICE_SET_1_DESK_2_SIDE_VAR_2 = block(MdmModBlocks.OFFICE_SET_1_DESK_2_SIDE_VAR_2);
		OFFICE_SET_1_BOOKSHELF_VAR_1_BOTTOM = block(MdmModBlocks.OFFICE_SET_1_BOOKSHELF_VAR_1_BOTTOM);
		OFFICE_SET_1_BOOKSHELF_VAR_1_TOP = block(MdmModBlocks.OFFICE_SET_1_BOOKSHELF_VAR_1_TOP);
		OFFICE_SET_1_SHELF_VAR_1_BOTTOM = block(MdmModBlocks.OFFICE_SET_1_SHELF_VAR_1_BOTTOM);
		OFFICE_SET_1_SHELF_VAR_1_TOP = block(MdmModBlocks.OFFICE_SET_1_SHELF_VAR_1_TOP);
		OFFICE_SET_1_SHELF_VAR_2_BOTTOM = block(MdmModBlocks.OFFICE_SET_1_SHELF_VAR_2_BOTTOM);
		OFFICE_SET_1_SHELF_VAR_2_TOP = block(MdmModBlocks.OFFICE_SET_1_SHELF_VAR_2_TOP);
		OFFICE_SET_1_DESK_1_CABINET = block(MdmModBlocks.OFFICE_SET_1_DESK_1_CABINET);
		OFFICE_SET_1_DESK_1_CABINET_VAR_2 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_CABINET_VAR_2);
		OFFICE_SET_1_DESK_1_CABINET_VAR_3 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_CABINET_VAR_3);
		OFFICE_SET_1_DESK_1_CABINET_VAR_4 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_CABINET_VAR_4);
		OFFICE_SET_1_DESK_1_LEFT = block(MdmModBlocks.OFFICE_SET_1_DESK_1_LEFT);
		OFFICE_SET_1_DESK_1_LEFT_VAR_2 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_LEFT_VAR_2);
		OFFICE_SET_1_DESK_1_LEFT_VAR_3 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_LEFT_VAR_3);
		OFFICE_SET_1_DESK_1_MIDDLE = block(MdmModBlocks.OFFICE_SET_1_DESK_1_MIDDLE);
		OFFICE_SET_1_DESK_1_RIGHT = block(MdmModBlocks.OFFICE_SET_1_DESK_1_RIGHT);
		OFFICE_SET_1_DESK_1_RIGHT_VAR_2 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_RIGHT_VAR_2);
		OFFICE_SET_1_DESK_1_RIGHT_VAR_3 = block(MdmModBlocks.OFFICE_SET_1_DESK_1_RIGHT_VAR_3);
		OFFICE_SET_1_CHAIR = block(MdmModBlocks.OFFICE_SET_1_CHAIR);
		OFFICE_SET_1_DESK_LAMP = block(MdmModBlocks.OFFICE_SET_1_DESK_LAMP);
		FURNITURE_PARTS = register("furniture_parts", LightOakFurniturePartsItem::new);
		BLACK_BENCH = block(MdmModBlocks.BLACK_BENCH);
		WHITE_BENCH = block(MdmModBlocks.WHITE_BENCH);
		CARPET_2 = block(MdmModBlocks.CARPET_2);
		CARPET_3 = block(MdmModBlocks.CARPET_3);
		CARPET_4 = block(MdmModBlocks.CARPET_4);
		WHITE_BOARD = block(MdmModBlocks.WHITE_BOARD);
		STANDING_WHITE_BOARD = block(MdmModBlocks.STANDING_WHITE_BOARD);
		CORK_BOARD = block(MdmModBlocks.CORK_BOARD);
		MODERN_PAINTING = block(MdmModBlocks.MODERN_PAINTING);
		MODERN_PAINTING_2 = block(MdmModBlocks.MODERN_PAINTING_2);
		WHITE_CURTAIN = block(MdmModBlocks.WHITE_CURTAIN);
		WHITE_CURTAIN_LEFT = block(MdmModBlocks.WHITE_CURTAIN_LEFT);
		WHITE_CURTAIN_RIGHT = block(MdmModBlocks.WHITE_CURTAIN_RIGHT);
		RED_CURTAIN = block(MdmModBlocks.RED_CURTAIN);
		RED_CURTAIN_LEFT = block(MdmModBlocks.RED_CURTAIN_LEFT);
		RED_CURTAIN_RIGHT = block(MdmModBlocks.RED_CURTAIN_RIGHT);
		CURTAIN_RACK = block(MdmModBlocks.CURTAIN_RACK);
		BLACK_CURTAIN = block(MdmModBlocks.BLACK_CURTAIN);
		BLACK_CURTAIN_LEFT = block(MdmModBlocks.BLACK_CURTAIN_LEFT);
		BLACK_CURTAIN_RIGHT = block(MdmModBlocks.BLACK_CURTAIN_RIGHT);
		GREY_CURTAIN = block(MdmModBlocks.GREY_CURTAIN);
		GREY_CURTAIN_LEFT = block(MdmModBlocks.GREY_CURTAIN_LEFT);
		GREY_CURTAIN_RIGHT = block(MdmModBlocks.GREY_CURTAIN_RIGHT);
		BLUE_CURTAIN = block(MdmModBlocks.BLUE_CURTAIN);
		BLUE_CURTAIN_LEFT = block(MdmModBlocks.BLUE_CURTAIN_LEFT);
		BLUE_CURTAIN_RIGHT = block(MdmModBlocks.BLUE_CURTAIN_RIGHT);
		GREEN_CURTAIN = block(MdmModBlocks.GREEN_CURTAIN);
		GREEN_CURTAIN_LEFT = block(MdmModBlocks.GREEN_CURTAIN_LEFT);
		GREEN_CURTAIN_RIGHT = block(MdmModBlocks.GREEN_CURTAIN_RIGHT);
		FOYER_WALL_UNIT_BOTTOM = block(MdmModBlocks.FOYER_WALL_UNIT_BOTTOM);
		FOYER_WALL_UNIT_TOP = block(MdmModBlocks.FOYER_WALL_UNIT_TOP);
		WHITE_WOOD_FOYER_WALL_UNIT = block(MdmModBlocks.WHITE_WOOD_FOYER_WALL_UNIT);
		WHITE_WOOD_FOYER_WALL_UNIT_TOP = block(MdmModBlocks.WHITE_WOOD_FOYER_WALL_UNIT_TOP);
		BLACK_FOYER_WALL_UNIT = block(MdmModBlocks.BLACK_FOYER_WALL_UNIT);
		BLACK_FOYER_WALL_UNIT_TOP = block(MdmModBlocks.BLACK_FOYER_WALL_UNIT_TOP);
		WHITE_ARMCHAIR = block(MdmModBlocks.WHITE_ARMCHAIR);
		BLACK_ARMCHAIR = block(MdmModBlocks.BLACK_ARMCHAIR);
		SMALL_TABLE = block(MdmModBlocks.SMALL_TABLE);
		SMALL_CHANDELIER = block(MdmModBlocks.SMALL_CHANDELIER);
		SMALL_CEILING_LAMP = block(MdmModBlocks.SMALL_CEILING_LAMP);
		BIG_CEILING_LIGHT = block(MdmModBlocks.BIG_CEILING_LIGHT);
		BIG_CEILING_LAMP = block(MdmModBlocks.BIG_CEILING_LAMP);
		BATHROOM_RADIATOR = block(MdmModBlocks.BATHROOM_RADIATOR);
		BATHROOM_SHELF_02 = block(MdmModBlocks.BATHROOM_SHELF_02);
		BOWL = block(MdmModBlocks.BOWL);
		CHOPPING_BOARD = block(MdmModBlocks.CHOPPING_BOARD);
		COFFEE_TABLE_04 = block(MdmModBlocks.COFFEE_TABLE_04);
		CRIB = block(MdmModBlocks.CRIB);
		FORK = block(MdmModBlocks.FORK);
		KNIFE = block(MdmModBlocks.KNIFE);
		KNIFE_STAND = block(MdmModBlocks.KNIFE_STAND);
		LAMP_03 = block(MdmModBlocks.LAMP_03);
		MUG = block(MdmModBlocks.MUG);
		PAINTING_05 = block(MdmModBlocks.PAINTING_05);
		PLATE = block(MdmModBlocks.PLATE);
		POTTED_CACTUS = block(MdmModBlocks.POTTED_CACTUS);
		POUF = block(MdmModBlocks.POUF);
		SEASONING_RACK = block(MdmModBlocks.SEASONING_RACK);
		SPOON = block(MdmModBlocks.SPOON);
		WALL_LAMP = block(MdmModBlocks.WALL_LAMP);
		WALL_LAMP_2 = block(MdmModBlocks.WALL_LAMP_2);
		WINDOW_BLINDS = block(MdmModBlocks.WINDOW_BLINDS);
		SHOJI_SCREEN = block(MdmModBlocks.SHOJI_SCREEN);
		PAINTING_03 = block(MdmModBlocks.PAINTING_03);
		PAINTING_04 = block(MdmModBlocks.PAINTING_04);
		BOXES = block(MdmModBlocks.BOXES);
		COAT_HANGER = block(MdmModBlocks.COAT_HANGER);
		DOOR_MAT = block(MdmModBlocks.DOOR_MAT);
		ELECTRIC_GUITAR_BLACK = block(MdmModBlocks.ELECTRIC_GUITAR_BLACK);
		ELECTRIC_GUITAR_WITH_STAND = block(MdmModBlocks.ELECTRIC_GUITAR_WITH_STAND);
		ENTRYWAY_CARPET = block(MdmModBlocks.ENTRYWAY_CARPET);
		FOYER_BENCH = block(MdmModBlocks.FOYER_BENCH);
		FOYER_BENCH_DARK = block(MdmModBlocks.FOYER_BENCH_DARK);
		FOYER_BENCH_WHITE = block(MdmModBlocks.FOYER_BENCH_WHITE);
		FOYER_BENCH_WENGE = block(MdmModBlocks.FOYER_BENCH_WENGE);
		PAIR_OF_BOOTS = block(MdmModBlocks.PAIR_OF_BOOTS);
		PAIR_OF_BOOTS_2 = block(MdmModBlocks.PAIR_OF_BOOTS_2);
		PAIR_OF_BOOTS_3 = block(MdmModBlocks.PAIR_OF_BOOTS_3);
		PAIR_OF_BOOTS_4 = block(MdmModBlocks.PAIR_OF_BOOTS_4);
		PAIR_OF_BOOTS_5 = block(MdmModBlocks.PAIR_OF_BOOTS_5);
		PAIR_OF_BOOTS_6 = block(MdmModBlocks.PAIR_OF_BOOTS_6);
		SHOE_RACK = block(MdmModBlocks.SHOE_RACK);
		SHOE_RACK_2 = block(MdmModBlocks.SHOE_RACK_2);
		SHOE_RACK_3 = block(MdmModBlocks.SHOE_RACK_3);
		TALL_MIRROR = block(MdmModBlocks.TALL_MIRROR);
	}

	private static ModRegistryEntry<Item> block(ModRegistryEntry<Block> block) {
		return block(block, new Item.Properties());
	}

	private static ModRegistryEntry<Item> block(ModRegistryEntry<Block> block, Item.Properties properties) {
		return register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static ModRegistryEntry<Item> register(String name, Supplier<? extends Item> factory) {
		return ModRegistryEntry.register(BuiltInRegistries.ITEM, name, factory::get);
	}

	public static void init() {
		// Invoking this method initializes the static registrations.
	}
}
