modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mdm"
version="${version}"
displayName="Modern Decorations Mod"
displayURL="https://cookiecraftmods.com/"
logoFile="logo.png"
authors="opaleq"
description='''
Adds modern decorative furniture, functional storage, refrigerators and ovens.
'''

[[dependencies.mdm]]
modId="neoforge"
type="required"
versionRange="[26.1.2.78,)"
ordering="NONE"
side="BOTH"

[[dependencies.mdm]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="BOTH"
