plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.141'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

tasks.withType(org.gradle.api.tasks.bundling.AbstractArchiveTask).configureEach {
    archiveVersion = "${project.mod_version}-${project.loader_name}-${project.minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
}

legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"

    runs {
        client {
            client()
            gameDirectory = file('run/client')
        }
        server {
            server()
            gameDirectory = file('run/server')
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir rootProject.file('../../shared/src/main/resources')
}

sourceSets.main.java {
    srcDir rootProject.file('../../shared/src/mc_1.20.1/java')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand 'mod_version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
}

apply from: rootProject.file('../../shared/gradle/validate-recipes.gradle')
